export default {
  SET_MOVIES: 'SET_MOVIES',
  SET_PAGE: 'SET_PAGE',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  TOGGLE_SEARCH: 'TOGGLE_SEARCH',
  REMOVE_MOVIE: 'REMOVE_MOVIE',
  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION'
};
